
import random
def banker_response(banker_cards: list[int]) -> int:
    bid_card = random.choice(banker_cards)
    banker_cards.remove(bid_card)
    return bid_card

def user_bid(banker_card: int, user_cards: list[int]) -> int:
    print(" Diamond card generated by Banker is: ", banker_card)
    bid = int(input("Enter your bid: "))
    if bid > 15 or bid < 2:
        print("ERROR: Enter again")
        user_bid(banker_card, user_cards)
    elif bid not in user_cards:
        print("ERROR: Already used your bid")
        user_bid(banker_card, user_cards)
    if bid in user_cards:
        user_cards.remove(bid)
    return bid

def bid_choice2(banker_card: int, card_list: list[int]) -> int:
        card_list.remove(banker_card)
        return banker_card
def determine_winner(user_card: int, computer_card: int, banker_card: int, user_points: int, computer_points: int) -> str:
    if user_card > computer_card:
        user_points += banker_card
        return "You won this round"
    if user_card < computer_card:
        computer_points += banker_card
        return "Computer won this round"
    else:
        user_points += banker_card / 2
        computer_points += banker_card / 2
        return "This was Tie"


def final_result(user_points: int, computer_points: int) -> str:
    if user_points > computer_points:
        return "Congratulations!! You won this game"
    if user_points < computer_points:
        return "OOPS!! You lost :("
    else:
        return "It's a tie"


def CARDS() -> str:
    check = "YES"
    while(check == "YES"):
        BANKER_CARDS = [i for i in range(2, 15)]
        USER_CARDS = [i for i in range(2, 15)]
        COMPUTER_CARDS= [i for i in range(2, 15)]
        User_points = 0
        Computer_points = 0
        Super_High_Cards = [13, 14]
        High_Cards = [10, 11, 12]
        Mid_Cards = [5, 6, 7, 8, 9]
        Low_Cards = [2, 3, 4]
        S_H_C,H_C, M_C, L_C  = Super_High_Cards, High_Cards, Mid_Cards, Low_Cards
        for chances in range(13):
            banker_card = banker_response(BANKER_CARDS)
            human_bid = user_bid(banker_card, USER_CARDS)
            computer_bid = bid_choice2(banker_card, COMPUTER_CARDS)
            print("computer_bid", computer_bid)
            print(determine_winner(human_bid, computer_bid, banker_card, User_points, Computer_points))
        print(final_result(User_points, Computer_points))
        check = input("Do you want to play again?(enter YES / NO)")

CARDS()
